### PR TITLE
Trigger observers when sending events

### PR DESCRIPTION
**Pull request by patrickariel**
This PR adds observer triggers for `TimeRunnerEnded` events.

Related: https://github.com/Multirious/bevy_tween/pull/44

### CODE REVIEW

**Comment by patrickariel** [comment]
Hey can I get some input @Multirious?

I'm working on a `0.15` migration for this repo and I noticed that `bevy_eventlistener` still depends on bevy `0.14` as of this writing, which means that it's currently not possible to migrate. So what do you think of just removing it as a dependency and using the built-in observer instead? It fulfills the role of `bevy_eventlistener` so well that I don't really see much reasons to keep both of them.

**Comment by Multirious** [comment]
When a new bevy is released, I will usually make a "migration" version, which is a version that does least breaking changes as much as possible for the ease of users, then I will make "enhancement" version where it will properly improves the plugin. You can submit some PR and mark it as blocking on bevy_eventlistener and maybe submit an issue to their crate to pressure the dev to get to work 😂. If they decided not to update the crate/would take too long the we probably can remove eventlistener.

**Comment by patrickariel** [comment]
`bevy_mod_picking` (along with `bevy_eventlistener`) is on track for deprecation now that they're both upstreamed, so not sure if it's worth waiting tbh. I don't think the author intends to update it for the current cycle.

**Comment by patrickariel** [comment]
Hey, any chance this could get merged so that I can base my `0.15` PR on top of it? Or are you planning one of your own?
Other than potentially dropping `bevy_eventlistener`, the only change you need is `delta_seconds` -> `delta_secs`.

**Comment by Multirious** [comment]
Yeah, I'll merge this shortly by today. I was taking care of stuffs.

**Pull request merged**
